### ISSUE TITLE
Input area isn't working right

### ISSUE THREAD

**Issue by SuperZing** [Federico-Ciuffardi/GestureControlledCamera2D#5]
If anchor mode is set to fixed topleft no touch gesture works. If anchor mode is set to drag center only a small portion to the left of my screen works correctly; then if I change the cameras limits the touch area just moves around. I just want it to work correctly and be able to set camera limits without the gesture touch area moving around the screen.

**Comment by SuperZing** [comment]
I found out the problem is based on the map image(textureRect) I have in the scene; depending on it's position in the screen it changes the input area. Also no touch gesture are working on the image

The green circle area is touchable.
![git2](https://user-images.githubusercontent.com/16162207/178074228-43f00420-7441-4ea7-abbd-945940ad15b9.jpg)

But if the image is like this then only this small green area is touchable.
![git](https://user-images.githubusercontent.com/16162207/178074537-200413dc-9b1e-409a-9fc1-b752e3904c76.jpg)

Writing this incase someone has the same problem as me

**Comment by Federico-Ciuffardi** [comment]
Check [this issue](https://github.com/Federico-Ciuffardi/GodotTouchInputManager/issues/12#issuecomment-747248780), maybe it will help you

**Comment by SuperZing** [comment]
Oh, thank you. I set the root node mouse to ignore, change the textureRect to a sprite and have everything center offset; now everything is working. Thank you again for helping me
